version: '3.7'
services:
  server:
    container_name: api-server
    restart: always
    build:
      context: .
      dockerfile: .Dockerfile.prod
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: api-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
